In [1]:
import pandas as pd
import os
from scipy import optimize
import numpy as np
print(os.listdir())

['.ipynb_checkpoints', 'data', 'Example_data_1.csv', 'Example_data_2.csv', 'Relative Ratios.ipynb']


In [11]:
result = pd.read_csv('Example_data_1.csv')
print(result)

      M10   M20  dM1/dM2
0   0.330  0.35   0.7900
1   0.081  0.91   0.0890
2   0.029  0.98   0.0096
3   0.280  0.31   0.8900
4   0.170  0.56   0.2600
5   0.320  0.89   0.4800
6   0.210  0.78   0.2400
7   0.460  0.77   0.8000
8   0.490  0.67   0.7900
9   0.280  0.31   0.8900
10  0.430  0.15   2.5000
11  0.094  0.53   0.1900
12  0.200  0.47   0.5300
13  0.320  0.44   1.0000
14  0.410  0.34   1.1000
15  0.470  0.28   1.9000
16  0.570  0.16   3.7000


In [18]:
#use this cell if you are fitting concentration data
result = pd.read_csv('Example_data_1.csv')

M1 = []
M2 = []
D = []
for i in range(len(result)):
    M1.append(result['M10'][i])
    M2.append(result['M20'][i])
    D.append(result['dM1/dM2'][i])
M10 = np.array(M1, dtype = float)
M20 = np.array(M2, dtype = float)
DM = np.array(D,dtype = float)

def func(x,r1,r2):
    m1,m2 = x
    return (m1*(r1*m1+m2))/(m2*(r2*m2+m1))

popt, pcov = optimize.curve_fit(func, (M10,M20), DM)
popt

array([0.93159438, 0.85424374])

In [16]:
#use this cell if you are fitting mole fraction data
result_mole = pd.read_csv('Example_data_2.csv')

f2 = []
F2 = []
for i in range(len(result_mole)):
    f2.append(result_mole['f2'][i])
    F2.append(result_mole['F2'][i])
f2 = np.array(f2, dtype = float)
F2 = np.array(F2, dtype = float)

def func(f2,r1,r2):
    return (r2*f2**2 + f2*(1-f2))/(r2*f2**2 +2*f2*(1-f2)+r1*(1-f2)**2)

popt, pcov = optimize.curve_fit(func, f2, F2)
popt

array([1.55384072, 0.51868127])

In [17]:
test = func(f2,1.56,0.52)
print(test)
print(F2)

[0.18749835 0.30050164 0.34621677 0.39778654 0.4778415  0.57238447
 0.63699606 0.77268526]
[0.192 0.295 0.351 0.408 0.467 0.576 0.622 0.787]
