In [1]:
import pandas as pd
import os
from scipy import optimize
import numpy as np
print(os.listdir())

['.ipynb_checkpoints', 'Example_data_1.csv', 'Example_data_2.csv', 'Relative Ratios.ipynb']


In [18]:
#use this cell if you are fitting concentration data
result = pd.read_csv('Example_data_1.csv')

M1 = []
M2 = []
D = []
for i in range(len(result)):
    M1.append(result['M10'][i])
    M2.append(result['M20'][i])
    D.append(result['dM1/dM2'][i])
M10 = np.array(M1, dtype = float)
M20 = np.array(M2, dtype = float)
DM = np.array(D,dtype = float)

def func(x,r1,r2):
    m1,m2 = x
    return (m1*(r1*m1+m2))/(m2*(r2*m2+m1))

popt, pcov = optimize.curve_fit(func, (M10,M20), DM)
popt

array([0.93159438, 0.85424374])

In [16]:
#use this cell if you are fitting mole fraction data
result_mole = pd.read_csv('Example_data_2.csv')

f2 = []
F2 = []
for i in range(len(result_mole)):
    f2.append(result_mole['f2'][i])
    F2.append(result_mole['F2'][i])
f2 = np.array(f2, dtype = float)
F2 = np.array(F2, dtype = float)

def func(f2,r1,r2):
    return (r2*f2**2 + f2*(1-f2))/(r2*f2**2 +2*f2*(1-f2)+r1*(1-f2)**2)

popt, pcov = optimize.curve_fit(func, f2, F2)
popt

array([1.55384072, 0.51868127])

In [17]:
test = func(f2,1.56,0.52)
print(test)
print(F2)

[0.18749835 0.30050164 0.34621677 0.39778654 0.4778415  0.57238447
 0.63699606 0.77268526]
[0.192 0.295 0.351 0.408 0.467 0.576 0.622 0.787]
